version : '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
      - /node_modules
  db:
    # platform: linux/x86_64  // if you are using on Mac M1 Chip
    image: mysql:8
    restart: always
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    