version: '3.9'

services:
  backend:
    container_name: backend-test
    command: sh -c "npm install && npm test"
    tty: true
  db:
    container_name: db-test
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root