version: '3.9'

services:
  backend:
    container_name: backend-dev
    command: npm run dev
    tty: true
    volumes:
      - .:/app
      - /node_modules
  db:
    container_name: db-dev
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root